#!/usr/bin/env python3
import os
import json
import gzip
import re
from collections import defaultdict

# --- Configuration ---
# Directory containing the YYYY.MM.js.gz files
data_dir = "data"
# Output JavaScript index file
output_file = os.path.join(data_dir, "index.js")
# Name of the JavaScript variable to store the index
js_variable_name = "ARCHIVE_INDEX"
# --- End Configuration ---

def create_archive_index(directory):
    """
    Scans the directory for YYYY.MM.js.gz files and creates an index.

    Args:
        directory (str): The path to the directory containing the data files.

    Returns:
        dict: A dictionary where keys are years (str) and values are sorted
              lists of months (str, e.g., "01", "02"). Returns None on error.
    """
    if not os.path.isdir(directory):
        print(f"Error: Data directory '{directory}' not found.")
        return None

    year_month_index = defaultdict(list)
    # Regex to match the required filename format
    filename_pattern = re.compile(r"^(\d{4})\.(\d{2})\.js\.gz$")

    print(f"Scanning directory: '{directory}'...")
    try:
        for filename in os.listdir(directory):
            match = filename_pattern.match(filename)
            if match:
                year = match.group(1)
                month = match.group(2)
                # Check if the file is actually a gzipped file (basic check)
                file_path = os.path.join(directory, filename)
                if os.path.isfile(file_path):
                     try:
                         # Try opening to see if it's a valid gzip file
                         with gzip.open(file_path, 'rb') as f:
                             f.read(1) # Read one byte to check validity
                         if month not in year_month_index[year]:
                              year_month_index[year].append(month)
                         print(f"  Found: {filename} (Year: {year}, Month: {month})")
                     except gzip.BadGzipFile:
                         print(f"  Skipping invalid gzip file: {filename}")
                     except Exception as e:
                          print(f"  Error reading file {filename}: {e}")


    except OSError as e:
        print(f"Error reading directory '{directory}': {e}")
        return None

    # Sort months numerically within each year
    for year in year_month_index:
        year_month_index[year].sort(key=int) # Sort months as integers

    # Convert defaultdict back to a regular dict for cleaner JSON output
    # and sort years
    sorted_index = dict(sorted(year_month_index.items()))


    print(f"Found data for years: {list(sorted_index.keys())}")
    return sorted_index

def write_index_js(index_data, output_path, var_name):
    """
    Writes the index data to a JavaScript file.

    Args:
        index_data (dict): The dictionary containing the year/month index.
        output_path (str): The full path for the output JavaScript file.
        var_name (str): The name for the JavaScript variable.
    """
    try:
        # Ensure the output directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"// Archive index generated by create-index.py\n")
            f.write(f"const {var_name} = ")
            # Use json.dump for proper formatting and escaping
            json.dump(index_data, f, indent=2, ensure_ascii=False)
            f.write(";")
        print(f"\nSuccessfully created index file: {output_path}")
    except IOError as e:
        print(f"Error writing index file '{output_path}': {e}")
    except Exception as e:
        print(f"An unexpected error occurred while writing the file: {e}")

# --- Main Execution ---
if __name__ == "__main__":
    print("Starting archive index generation...")
    archive_data = create_archive_index(data_dir)

    if archive_data is not None:
         if not archive_data:
              print("\nWarning: No valid data files found. Index file will be empty.")
         write_index_js(archive_data, output_file, js_variable_name)
    else:
        print("\nIndex generation failed.")

    print("Script finished.")

